version: "3.9"

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  app:
    build: .
    env_file:
      - .env
    environment:
      - DB_HOST=mongodb
      - WAIT_HOSTS=mongodb:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=2
      - WAIT_HOST_CONNECT_TIMEOUT=5
    command: sh -c "/wait && cd /usr/app/src && python main.py"
    depends_on:
      - mongodb
    volumes:
      - ./src:/usr/app/src
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3

volumes:
  mongodb:
    name: ${PROJECT_NAME}_db